name: "build"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Checkout candid repo
      uses: actions/checkout@v2
      with:
        repository: dfinity/candid
    - name: Install candid tools
      run: |
       cd tools/didc
       cargo install --root /home/runner --path .
       cd ..
       cd candiff
       cargo install --root /home/runner --path .
       cd ../..
       echo "::add-path::/home/runner/bin"
    - uses: actions/checkout@v2
    - name: "didc help (sanity check)"
      run: didc --help
    - name: "candiff help (sanity check)"
      run: candiff --help
    - name: "install dfx"
      run: |
       wget https://sdk.dfinity.org/install.sh
       echo DFX_VERSION=0.6.0
       yes Y | DFX_VERSION=0.6.0 sh install.sh
       echo "::add-path::/home/runner/bin"
    - name: "dfx cache install"
      run: dfx cache install
    - name: "install vessel"
      run: wget --output-document /home/runner/bin/vessel https://github.com/kritzcreek/vessel/releases/download/v0.4.1/vessel-linux64 && chmod +x /home/runner/bin/vessel
    - name: "test"
      run: ./test.sh