name: "build"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DFX_VERSION: 0.13.1
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |      
        echo y | DFX_VERSION=$DFX_VERSION bash -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
        echo "/home/runner/bin" >> $GITHUB_PATH
        npm i -g ic-mops
    - name: Build
      run: |
        set -x
        dfx cache install
        dfx start --background
        dfx canister --no-wallet create Search
        dfx build Search
        dfx deploy --no-wallet Search
        dfx canister --no-wallet create UnitTest
        dfx build UnitTest
        dfx deploy --no-wallet UnitTest
        dfx canister call UnitTest selfTest
    - name: "docs"
      run: /home/runner/.cache/dfinity/versions/$DFX_VERSION/mo-doc
    - name: Upload docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/
