name: "build"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: "install dfx"
      run: |
       wget https://sdk.dfinity.org/install.sh
       yes Y | DFX_VERSION=0.7.0-beta.3 sh install.sh
       echo "/home/runner/bin" >> $GITHUB_PATH
    - name: "dfx cache install"
      run: dfx cache install
    - name: "install vessel"
      run: ./scripts/vessel-install.sh
    - name: "test"
      run: ./scripts/test.sh