name: "build"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DFX_VERSION: 0.7.5
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        echo y | DFX_VERSION=$DFX_VERSION bash -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
        echo "/home/runner/bin" >> $GITHUB_PATH
        ./scripts/vessel-install.sh
    - name: Build
      run: |
        dfx cache install
        dfx start --background
        dfx deploy --no-wallet BigSearch
    - name: "docs"
      run: /home/runner/.cache/dfinity/versions/0.7.5/mo-doc
    - name: Upload docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/%
